# Generated by Django 3.1.7 on 2021-04-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='org',
            field=models.CharField(default='org', max_length=100),
        ),
    ]
