# Generated by Django 3.1.7 on 2021-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='org',
            field=models.CharField(default='', max_length=100),
        ),
    ]
