# Generated by Django 3.1.7 on 2021-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_image_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
