# Generated by Django 3.1.7 on 2021-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_image_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hog',
            field=models.CharField(default='', max_length=100),
        ),
    ]
