# Generated by Django 3.1.7 on 2021-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_image_hog'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='reg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
