# Generated by Django 3.1.7 on 2021-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_image_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hogph',
            field=models.CharField(default='', max_length=100),
        ),
    ]
