# Generated by Django 3.1.7 on 2021-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_image_accno'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
