# Generated by Django 3.1.7 on 2021-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0015_image_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pin',
            field=models.IntegerField(default=''),
        ),
    ]
