# Generated by Django 3.1.7 on 2021-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0016_auto_20210416_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='ngo_contact_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
