# Generated by Django 3.1.7 on 2021-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0017_auto_20210419_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
