# Generated by Django 3.1.7 on 2021-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0021_auto_20210507_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='accno',
            field=models.IntegerField(default=''),
        ),
    ]
