# Generated by Django 3.1.7 on 2021-05-08 19:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0022_auto_20210507_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hogph',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
