# Generated by Django 3.1.7 on 2021-05-08 20:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0023_auto_20210509_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ngo_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
