# Generated by Django 3.1.7 on 2021-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0024_auto_20210509_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.DateField(default=''),
        ),
    ]
