# Generated by Django 3.1.7 on 2021-04-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngouser',
            old_name='Email',
            new_name='email',
        ),
    ]
