# Generated by Django 3.1.7 on 2021-04-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20210409_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NgoUser',
        ),
    ]
