# Generated by Django 3.1.7 on 2021-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210411_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
