# Generated by Django 3.1.7 on 2021-04-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_add_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_user',
            old_name='img',
            new_name='image',
        ),
    ]
