# Generated by Django 3.1.7 on 2021-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210412_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='image',
            field=models.URLField(),
        ),
    ]
