# Generated by Django 3.1.7 on 2021-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210413_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_feed',
            fields=[
                ('ngo_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
