# Generated by Django 3.1.7 on 2021-04-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210413_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_feed',
            old_name='ngo_id',
            new_name='feed_id',
        ),
    ]
