# Generated by Django 3.1.7 on 2021-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20210413_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_feed',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
