# Generated by Django 3.1.7 on 2021-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_postimg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='postimg',
            name='ngo_contact_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
