# Generated by Django 3.1.7 on 2021-04-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20210418_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimg',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='postimg',
            name='ngo_contact_no',
        ),
    ]
