# Generated by Django 3.1.7 on 2021-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20210425_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField(default='0')),
                ('type', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
