# Generated by Django 3.1.7 on 2021-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_donatestationary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('type', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
