# Generated by Django 3.1.7 on 2021-05-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0026_donateblood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_user',
        ),
    ]
